version: '3.5'

services:
  angular-service:
    container_name: angular-service-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4200:4200'
