version: '3.8'
services:
  tech-db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=demo3
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=Linux_ubuntu1
      - MYSQL_HOST=jdbc:mysql://localhost/
#    volumes:
#      - /opt/mysql_data:/var/lib/mysql
#      - ./:/project
  demo3:
    depends_on:
      - tech-db
    image: shree/tech
    volumes:
      - /home/shree/lab/server/apache-tomcat-9.0.54/conf/config:/usr/local/tomcat/conf/config
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://tech-db:3306/demo3'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'root'
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: 'com.mysql.cj.jdbc.Driver'